### ISSUE TITLE
Libtrust status?

### ISSUE THREAD

**Issue by snrism** [docker/libtrust#51]
Hi,

Wanted to check if libtrust is still actively maintained and if new PRs are accepted? Or have you migrated this activity to any other repo? Thanks.

**Comment by dmcgowan** [comment]
It is still maintained, if you have bug fixes please submit a PR. If you have a feature request, please open up an issue or proposal PR.  Expect some interfaces to change and additional functionality which better defines libtrust's purpose apart from a set of primitives and helper functions.

**Comment by snrism** [comment]
thanks for the info
