### ISSUE TITLE
Tagging a version of libtrust (v0.1.0)

### ISSUE THREAD

**Issue by vdemeester** [docker/libtrust#55]
It would be very cool to have a tag for `libtrust`, for applying the _vendoring_ policy of `docker/docker`, see https://github.com/docker/docker/blob/3d13fddd2bc4d679f0eaa68b0be877e5a816ad53/VENDORING.md.

I propose `v0.1.0` :angel: 

/cc @icecrime @thaJeztah @dmcgowan

**Comment by thaJeztah** [comment]
agreed; I see there's some (very old) PR's open though; should we merge those before, or after?

**Comment by vdemeester** [comment]
@thaJeztah given the timebox for `v1.12.0` I would definitely tag it before merging them (and tagging the current vendored commit in `docker/docker` which is c8d2b36d60a84f3fa7d5e5e355be64f0fbe0b481).

**Comment by dmcgowan** [comment]
I would prefer not adding any tags to this repository since it is no longer developed, likewise with merging PRs. The functionality in this repository has been discussed being moved into distribution or a Docker `pkg` since it is no longer providing any feature within Docker, only helpers for signing and key management.

**Comment by vdemeester** [comment]
@dmcgowan hum I see, fair enough :wink:. what is the status of this discussions / moves ? any need to help on moving things forward ? (here and thus on the docker/docker vendoring too)

**Comment by thaJeztah** [comment]
@dmcgowan @vdemeester opened a PR to add a warning; https://github.com/docker/libtrust/pull/56

**Comment by dmcgowan** [comment]
@vdemeester slated code migration to distribution in the 2.6 release, which will correspond with Docker 1.13. If this repo needs a tag until then for 1.12 then I can accommodate, my personal feeling is attaching a version number does not provide more meaning than a commit hash without the accompanying changelog.
